### ISSUE TITLE
utils.misc.py needs to be broken up

### ISSUE THREAD

**Issue by phobson** [Geosyntec/wqio#67]
At the most granular, it could be:
  1. latexutils (sanitizeTex, LaTexDirectory)
  1. stringutils (formatResult)
  1. ioutils (csvToXlsx)
  1. dfutils (addSecondColumnLevel)
  1. numutils (process_p_vals, fit_line)
  1. dateutils (getSeason, sanitizeTimestamp)
  

We don't need all of these, and some function definitely overlap. We should just find to 1 - 3 categories that are the most clear-cut, break those out, and leave everything else in misc.py

@lucashtnguyen I welcome your thoughts.

**Comment by lucashtnguyen** [comment]
Maybe something like this?

1. dateutils
    - santizeTimestamp
    - getSeason
    - makeTimestamp
    - getWaterYear

2. numutils
    - sigFigs
    - _sig_figs
    - formatResult
    - normalize_units
    - normalize_units2
    - pH2concentration
    - estimateFromLineParams
    - checkIntervalOverlap
    - fit_line
    - processAndersonDarlingResults

3. reportutils
    - 3a. pltutils
        + _boxplot_legend
        + makeBoxplotLegend
        + whiskers_and_fliers
    - 3b. latexutils
        + makeTexTable
        + makeLongLandscapeTexTable
        + makeTexFigure
        + sanitizeTex
    - 3c. other
        + stringify

4. misc
    - nested_getattr
    - 4a. dfutils
        + addSecondColumnLevel
        + getUniqueDataframeIndexVal
        + redefineIndexLevel
    - 4b. ioutils
        + processFilename
        + csvToTex
        + csvToXlsx
